___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print(np.__version__)
np.show_config()


1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']


Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
x = np.ones(10) 
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [4]:
x = np.arange(0,11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [5]:
x = np.zeros(25).reshape(5,5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [6]:
x = np.random.randint(0, 10, 10)
print(x)
nz = np.nonzero(x)
print(nz)

[3 0 2 5 1 0 5 2 9 2]
(array([0, 2, 3, 4, 6, 7, 8, 9], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [7]:
m = x.mean()
print(m)
m = np.median(x)
print(m)
m = np.std(x)
print(m)

2.9
2.0
2.6248809496813372


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [8]:
x = np.random.randint(0, 10, (4, 2))
y = np.random.randint(0, 10, (2, 2))
print(x)
print(y)
prod = x.dot(y)
print(prod)

[[5 8]
 [5 7]
 [6 6]
 [7 0]]
[[1 9]
 [2 5]]
[[21 85]
 [19 80]
 [18 84]
 [ 7 63]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [9]:
vect=np.reshape(prod, (1, 8))[0]
print(vect)

Zmin, Zmax = vect.min(), vect.max()
print(Zmin, Zmax)

vect[np.argmax(vect)]=0
print(vect)


[21 85 19 80 18 84  7 63]
7 85
[21  0 19 80 18 84  7 63]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [12]:
first = prod[0] 

without_first = np.delete(prod, (0), axis=0) 

for i in without_first:                   
    print(np.correlate(first, i))

[399]
[378]
[147]


Дано матрицю. Знайти ранг матриці:

In [61]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
print(np.linalg.matrix_rank(a))

3


Знайти визначник матриці:

In [62]:
print(np.linalg.det(a))

440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [63]:
print(np.linalg.eigh(a))

(array([-14.30540864,  -4.34740072,  23.65280936]), array([[ 0.15315575,  0.88160309,  0.44645191],
       [ 0.63674998, -0.43353159,  0.6376518 ],
       [-0.75570681, -0.18661821,  0.62775861]]))


Знайдіть число, що найчастіше зустрічається в масиві:

In [66]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())

[4 3 0 6 2 0 9 8 6 6 7 3 6 9 0 4 7 9 0 9 4 9 9 2 5 8 5 5 7 0 7 5 1 7 9 8 6
 8 3 7 2 3 0 8 7 8 8 4 5 6]
7


Виведіть лише парні числа, що діляться на 5:

In [17]:
a = np.random.randint(0,100,50)
print(a)
a=np.array([a for a in a if (a % 2 == 0) and (a % 5 == 0) and (a != 0)])
print(a) 

[94 22 69 15 95 97 29 83 28 43 12 51 87 69 31 43 35 10 62 84 42 95 60 97
 78 73  7 32 58 32 69 23 36 61 28 21 17 63 23 98 31 50 44 52 96 11 20 79
 31  8]
[10 60 50 20]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [84]:
m = np.array([[2., 5.], [1., -10.]])
v = np.array([1., 3.])
np.linalg.solve(m, v)

array([ 1. , -0.2])